### ISSUE TITLE
errors when iterating a path

### ISSUE THREAD

**Issue by zhubonan** [zhubonan/aiida-grouppathx#2]
When iterating a path, but also activelty altering the database, an error is thrown at the end

```

07/08/2022 04:34:32 PM <6004> sqlalchemy.pool.impl.QueuePool: [ERROR] Error closing cursor
Traceback (most recent call last):
  File "/home/bonan/miniconda3/envs/aiida-2.0/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 1100, in fetchmany
    new = dbapi_cursor.fetchmany(size - lb)
psycopg2.ProgrammingError: named cursor isn't valid anymore

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bonan/miniconda3/envs/aiida-2.0/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1914, in _safe_close_cursor
    cursor.close()
psycopg2.ProgrammingError: named cursor isn't valid anymore

```

Example code template:

```
for path in base_path:
    .... do ... somthing
    submit(builder)
```

One way to get around this issue is to collect the iteration results first. 

```
for path in list(base_path):
    .... do ... somthing
    submit(builder)
```

This did not raise any issue in AiiDA v1. Perhpas the collection of iteration results should be the default behaviour?

**Comment by zhubonan** [comment]
already solved
